version: "3.8"
services:
  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
volumes:
  postgres_db:
